### 新增商品
# @no-cookie-jar
POST http://localhost:8030/mall-product/product/admin/spu/create
Content-Type: application/json
satoken: 61cf6398-b69d-44e6-8e40-3d7c55397a73

{
  "picUrl": "http://localhsot:8080/pic",
  "name": "测试商品2",
  "summary": "这是测试商品2",
  "price": 100,
  "stock": 90,
  "type": 1,
  "status": 1
}


### 删除商品
# @no-cookie-jar
GET http://localhost:8030/mall-product/product/admin/spu/delete?ids=2
Content-Type: application/json
satoken: 61cf6398-b69d-44e6-8e40-3d7c55397a73


### 更新商品
# @no-cookie-jar
POST http://localhost:8030/mall-product/product/admin/spu/update
Content-Type: application/json
satoken: 61cf6398-b69d-44e6-8e40-3d7c55397a73

{
  "id": 1,
  "picUrl": "http://localhsot:8080/pic",
  "name": "测试商品1",
  "summary": "这是测试商品1",
  "price": 100,
  "stock": 90,
  "type": 0,
  "status": 1,
  "memberLevelId": null
}


### 商品分页
# @no-cookie-jar
GET http://localhost:8030/mall-product/product/admin/spu/get/page
Content-Type: application/json
satoken: 61cf6398-b69d-44e6-8e40-3d7c55397a73


### 商品详情
# @no-cookie-jar
GET http://localhost:8030/mall-product/product/admin/spu/get/by-id/2
Content-Type: application/json
satoken: 61cf6398-b69d-44e6-8e40-3d7c55397a73
