### 确认订单
# @no-cookie-jar
POST http://localhost:8010/mall-trade/trade/app/order/confirm
Content-Type: application/json
satoken: 8e5aa39b-edb6-42cc-8fcb-2bb54ba50350

{
  "list": [
    {
      "spuId": 100,
      "quantity": 2
    },
    {
      "spuId": 101,
      "quantity": 3
    }
  ]
}


### 提交订单
# @no-cookie-jar
POST http://localhost:8010/mall-trade/trade/app/order/submit
Content-Type: application/json
satoken: 8e5aa39b-edb6-42cc-8fcb-2bb54ba50350

{
  "orderToken": "6ad63fbafe9b4c2b9e9fd56fbd017f0b",
  "orderItems": [
    {
      "spuId": 100,
      "spuName": "方天画戟",
      "picUrl": "https://localhost:8080/pic",
      "price": 500,
      "quantity": 2,
      "type": 0
    },
    {
      "spuId": 101,
      "spuName": "赤兔马",
      "picUrl": "https://localhost:8080/pic",
      "price": 450,
      "quantity": 3,
      "type": 0
    }
  ],
  "paymentAmount": 2350
}


### 支付订单
# @no-cookie-jar
POST http://localhost:8010/mall-trade/trade/app/order/pay
Content-Type: application/json
satoken: 8e5aa39b-edb6-42cc-8fcb-2bb54ba50350

{
  "orderSn": "fb76cc600d894439836174fdaabff117",
  "paymentMethod": 0
}
