spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/haoyuan?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: 1 # 0：不应答，1：leader 应答，all：所有 leader 和 flower 应答
      retries: 3 # 发送失败重试次数
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest # todo 这是啥
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              packages:
    listener:
      missing-topics-fatal: false # 消费者监听的主题不存在时不会报错

