server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8010

spring:
  application:
    name: haoyuan-gateway
  profiles:
    active: @profileActive@
  main:
    web-application-type: reactive

logging:
  config: classpath:logback-haoyuan-gateway.xml
