server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8010

spring:
  application:
    name: mall-gateway
  profiles:
    active: @profileActive@
  main:
    web-application-type: reactive

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/mall-auth?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

sa-token:
  token-name: satoken
  # token 存活时间（秒），-1 永久
  timeout: 2592000
  # token 最低活跃频率（秒）,超过指定时间冻结 token
  active-timeout: -1
  # 是否允许同一账号多地同时登录
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token
  is-share: true
  token-style: uuid
  is-log: true

logging:
  config: classpath:logback-blog.xml
