spring:
  data:
    redis:
      # Redis服务器地址
      host: 127.0.0.1
      # Redis服务器连接端口
      port: 6379
      # Redis服务器连接密码（默认为空）
      # password:
      # 连接超时时间
      timeout: 10s
      lettuce:
        pool:
          # 连接池最大连接数
          max-active: 200
          # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池中的最小空闲连接
          min-idle: 0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mall-sys
          order: 1
          uri: lb://mall-sys # 路由的地址
          predicates:
            - Path=/mall-sys/** # 路由匹配的路径
          filters:
            - StripPrefix=1 # 转发时去除前缀1层路径
        - id: mall-auth
          order: 2
          uri: lb://mall-auth
          predicates:
            - Path=/mall-auth/**
          filters:
            - StripPrefix=1
        - id: mall-member
          uri: lb://mall-member
          predicates:
            - Path=/mall-member/**
          filters:
            - StripPrefix=1
        - id: mall-product
          uri: lb://mall-product
          predicates:
            - Path=/mall-product/**
          filters:
            - StripPrefix=1
        - id: mall-trade
          uri: lb://mall-trade
          predicates:
            - Path=/mall-trade/**
          filters:
            - StripPrefix=1
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/mall-auth/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8060/auth/rsa/public-key'