server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8020
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /sys

spring:
  application:
    name: mall-sys
  profiles:
    active: @profileActive@
  messages:
    encoding: UTF-8
    basename: i18n/message
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

feign:
  httpclient:
    hc5:
      enabled: true
    max-connections: 200
    max-connections-per-route: 50

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.limyel.haoyuan.mall.*.entity
  global-config:
    #数据库相关配置
    db-config:
      id-type: auto
      logic-delete-value: NOW()
      logic-not-delete-value: 'NULL'
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'NULL'
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE

sa-token:
  token-name: satoken
  # token 存活时间（秒），-1 永久
  timeout: 2592000
  # token 最低活跃频率（秒）,超过指定时间冻结 token
  active-timeout: -1
  # 是否允许同一账号多地同时登录
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token
  is-share: true
  token-style: uuid
  is-log: true
  check-same-token: true

logging:
  config: classpath:logback-blog.xml