server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8010

spring:
  application:
    name: cloud-gateway
  profiles:
    active: @profileActive@
  main:
    web-application-type: reactive
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  config: classpath:logback-cloud-gateway.xml
