### 添加文章
POST http://127.0.0.1:8888/blog/admin/post/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsaW15ZWwiLCJpc3MiOiJsaW15ZWwiLCJpYXQiOjE3MjM3OTM5NjQsImV4cCI6MTcyNDIyNTk2NH0.I1-mQ7jA5Lz4UZxyRyEETIwaWwD5ATs5ZP-I43IqlGMxqLH1BhtEZooO-suL2E3Q2zTrKHQWmfPVpe-XATTYqQ

{
  "title": "test post 1",
  "slug": "test-post-1",
  "content": "test1test1test1test1test1",
  "top": false,
  "status": 1,
  "tagIds": [1]
}


### 删除文章
GET http://127.0.0.1:8888/blog/admin/post/delete/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsaW15ZWwiLCJpc3MiOiJsaW15ZWwiLCJpYXQiOjE3MjM3OTM5NjQsImV4cCI6MTcyNDIyNTk2NH0.I1-mQ7jA5Lz4UZxyRyEETIwaWwD5ATs5ZP-I43IqlGMxqLH1BhtEZooO-suL2E3Q2zTrKHQWmfPVpe-XATTYqQ



###
GET http://127.0.0.1:8888/blog/admin/post/get/page
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJsaW15ZWwiLCJpc3MiOiJsaW15ZWwiLCJpYXQiOjE3MjM3OTM5NjQsImV4cCI6MTcyNDIyNTk2NH0.I1-mQ7jA5Lz4UZxyRyEETIwaWwD5ATs5ZP-I43IqlGMxqLH1BhtEZooO-suL2E3Q2zTrKHQWmfPVpe-XATTYqQ
