###
# @no-cookie-jar
POST http://localhost:8030/mall-auth/auth/token/login
Content-Type: application/json

{
  "authInfo": "{\"username\": \"test\",\"password\": \"123456\"}",
  "loginType": "admin",
  "authType": "password"
}


###
# @no-cookie-jar
POST http://localhost:8030/mall-auth/auth/token/login
Content-Type: application/json

{
  "authInfo": "{\"username\": \"test1\",\"password\": \"123456\"}",
  "loginType": "user",
  "authType": "password"
}


###
POST http://localhost:8030/mall-auth/auth/token/logout
Content-Type: application/json

{

}