db.driver.name=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/haoyuan?useUnicode=true&characterEncoding=utf8
db.username=root
db.password=123456


table.ignore.prefix=false
table.exclude.list=flyway_schema_history


config.project=com.limyel.haoyuan
config.target.path=/tmp